server:
  port: 9092
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application.name: UserDataAPI

  r2dbc:
    url: r2dbc:mysql://localhost:3306/mydb
    username: root
    password: mypassword
    driver-class-name: org.mysql.Driver
    pool.enabled: true
    pool.initial-size: 5
    pool.max-size: 10

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: root
    password: mypassword
    url: jdbc:mysql://localhost:3306/mydb

management:
  endpoints:
    web:
      exposure.include: "health,prometheus"
      base-path: /
      path-mapping.prometheus: "metrics"
    jmx.exposure.exclude: "*"
  metrics:
    enable.jvm: true
    distribution:
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        "[http.server.requests]": "10ms,50ms,100ms,200ms,500ms,1s,5s,10s,30s"

logging:
  level:
    org.springframework.r2dbc: WARN
    org.flywaydb: DEBUG
