services:

  # Applications

  user-api-service:
    depends_on:
      usermysql:
        condition: service_healthy
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
      alertmanager:
        condition: service_started
    image: "user-data-api-docker-image"
    container_name: "user-data-api-docker-image"
    ports:
      - "9092:9092"
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://usermysql:3306/mydb

  # Backing Services

  usermysql:
    image: "mysql/mysql-server"
    container_name: "user-mysql"
    depends_on:
      - grafana
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  # Observability

  grafana:
    image: grafana/grafana-oss:10.4.3
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password

  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - alertmanager

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"