global:
  scrape_interval: 2s
  evaluation_interval: 15s

rule_files:
  - "../alertmanager/alert-rules.yml"

scrape_configs:
  - job_name: 'user-service'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'user-api-service:9092' ]
  - job_name: 'prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'localhost:9090' ]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]